name: "Sample Action"
description: "Test how action work"
author: "ivuorio@gmail.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Test"
  runs:
    using: "docker"
    image: "Dockerfile"
  branding:
    icon: "mic"
    color: "red"