name: workflow for my test file in docker in docker
on: push
jobs:
  build:
    name: Test action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./action-a
      with: 
        TOP_SECRET: ${{secrets.TOP_SECRET}}
